<?php
/**
 * Created by PhpStorm.
 * User: bengeos
 * Date: 6/17/17
 * Time: 1:08 PM
 */

namespace MembersManager\Controller;


use Doctrine\ORM\EntityManager;
use Zend\Mvc\Controller\AbstractRestfulController;

class MembersController extends AbstractRestfulController
{
    /**
     * @var EntityManager $EntityManager
     */
    protected $EntityManager;


    public function get($id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }
    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }
    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}